<div class="divide10"></div>
<div class="container">
	<ol class="breadcrumb">
		<li><a href="$context$index.xhtml">Home</a></li>
		<li class="active">Error</li>
	</ol>
	<div class="row">
		<div class="col-md-12 text-center error-text">
			<div class="divide30"></div>
			<h1 class="error-digit wow animated fadeInUp margin20">
				<i class="fa fa-thumbs-down"></i>
			</h1>
			<h2>Opps, the page could not be found!</h2>
			<p>
				<a href="$context$index.xhtml" class="btn border-black btn-lg">Go Back</a>
			</p>
		</div>
	</div>
</div>