<div class="divide10"></div>
<ol class="breadcrumb">
		<li><a href="index.xhtml">Home</a></li>
		<li class="active">FAQ</li>
	</ol>
	$if(cssId)$
	<div class="alert $cssId$" role="alert">$message$</div>
	$endif$
	
<div class="panel panel-default">
	<div class="panel-heading">
		<h2 class="panel-title">Frequent Ask Questions</h2>
	</div>
	<div class="panel-body">
		<ol>
			<li><b>What is a ItCertification2?</b></li>
			<ul>
				<li>A social community site for IT professionals, where IT people
					can practice their exam on-line, communicate with other professionals
					who are in the same field, share and exchange questions and answers.</li>
			</ul>

			<li><b>What services does ItCertification2 provide?</b></li>
			<ul>
				<li>A Social Network community for IT certified</li>
				<li>Online real-time simulation</li>
				<li>Online practice test</li>
				<li>IT Certification Community Forum</li>
				<li>User exam update interface, which allows end-users to
					update the exam content</li>
			</ul>

			<li><b>How often the exam be updated?</b></li>
			<ul>
				<li>This is community certification site so exams are updated
					by the professional IT like you. ItCertification2 provide access to users
					who has taken the certification and are willing to update the mock
					exams to reflect new changes in real exams. Also ItCertification2 hires a
					group of IT students to continue write new mock exam and update the
					exam content.</li>
			</ul>
			<br />
			<li><b>How effective mock exams comparing to the real
					certification tests?</b></li>
			<ul>
				<li>Though there is no such mock exam that can help test takers
					to pass the test without studying the materials provided by vendors
					and real world experience. These mock exams can help the test
					takers to build their confidence prior to taking the actual exams and
					to share their lesson learn with others in the community</li>
			</ul>
			<br />
			<li><b>Requirement for using ItCertification2 online exam
					simulation and practice?</b></li>
			<ul>
				<li>ItCertification2 exam simulation engine and practice test are
					built using leading edge technology. As long as you have access to
					the Internet, you can access online exam simulation engine or
					practice test using your favourite browser. Our goal is to continue
					to improve the exam simulation engine. Feedback from users like you
					is greatly appreciated!</li>
			</ul>
		</ol>
	</div>
</div>