<!DOCTYPE html>
<html lang="en">
	$sub/header()$
 <body id="boxed">
<div class="boxed-wrapper">
	$sub/topnav()$
  	$sub/nav()$
  	$body$
  	$sub/footer()$
</div>

<!--scripts and plugins -->
	<!--must need plugin jquery-->
	<script src="$context$js/jquery.min.js"></script> 
	<script src="$context$js/jquery-migrate.min.js"></script>
	<script src="$context$js/bootstrap.min.js" type="text/javascript"></script>

	
	<!--bootstrap js plugin-->
	
	<!--easing plugin for smooth scroll-->
	<script src="$context$js/jquery.easing.1.3.min.js" type="text/javascript"></script>
	<!--sticky header-->
	<script type="text/javascript" src="$context$js/jquery.sticky.js"></script>
	<!--flex slider plugin-->
	<script src="$context$js/jquery.flexslider-min.js" type="text/javascript"></script>
	<!--parallax background plugin-->
	<script src="$context$js/jquery.stellar.min.js" type="text/javascript"></script>


	<!--digit countdown plugin-->
	<script
		src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
	<!--digit countdown plugin-->
	<script src="$context$js/jquery.counterup.min.js" type="text/javascript"></script>
	<!--on scroll animation-->
	<script src="$context$js/wow.min.js" type="text/javascript"></script>
	<!--owl carousel slider-->
	<script src="$context$js/owl.carousel.min.js" type="text/javascript"></script>
	<!--popup js-->
	<script src="$context$js/jquery.magnific-popup.min.js" type="text/javascript"></script>
	<!--you tube player-->
	<script src="$context$js/jquery.mb.YTPlayer.min.js" type="text/javascript"></script>


	<!--customizable plugin edit according to your needs-->
	<script src="$context$js/custom.js" type="text/javascript"></script>


    <script src="$context$js/jquery.equalheights.js"></script>
    
    <!--[if (gt IE 9)|!(IE)]><!-->
  

</body>
</html>
