<ol class="breadcrumb">
		<li><a href="index.xhtml">Home</a></li>
		<li class="active">Salaries by IT Certifications</li>
	</ol>
<div class="divide10"></div>
<div class="container">
	
	<div class="panel panel-default">
		<div class="panel-heading">Salary by Certification</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-md-2 col-md-offset-5">
					<div
						style="background: white; color: #333; font: normal 11pt Verdana, Arial, sans-serif; text-align: center; border: 1px solid #96b9d7; padding: 5px; width: 510px">
						<a
							href="http://www.payscale.com/research/US/Certification=CompTIA%2fNetwork_Technician/Salary/by_Job"
							style="color: #06C; text-decoration: none; font-weight: bold;">Median
							Salary by Job - Certification: CompTIA/Network Technician (United
							States)</a> <a
							href="http://www.payscale.com/research/US/Certification=CompTIA%2fNetwork_Technician/Salary/by_Job"><img
							src="http://www.payscale.com/research/US/Certification=CompTIA%2fNetwork_Technician/Salary/by_Job.png"
							alt="Median Salary by Job" border="0" /></a>

					</div>
				</div>
			</div>


		</div>
	</div>
</div>
