<div class="jumbotron">
		<div class="row">
		<div class="col-md-2"></div>
			<div class="col-md-8">
				<div class="input-group">
					<input type="text" class="form-control"
						placeholder="Search here ..."> <span
						class="input-group-btn">
						<button class="btn btn-theme-bg btn-lg" type="button" onclick="alert('Search...');">
							<i class="fa fa-search"></i>
						</button>
					</span>
				</div>
			</div>
			<div class="col-md-2"></div>
		</div>
</div>

