<footer id="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-sm-6 margin30">
				<div class="footer-col">
					<h3>Popular Certifications</h3>
					<ul class="footer_list">
						<li><a href="mining.xhtml">Microsoft</a></li>
						<li><a href="data.xhtml">Oracle</a></li>
						<li><a href="software.xhtml">Cisco</a></li>
						<li><a href="web.xhtml">Linux</a></li>
					</ul>
				</div>
			</div>
			<!--footer col-->
			<div class="col-md-4 col-sm-6 margin30">
				<div class="footer-col">
					<h3>Contact</h3>
					<ul class="list-unstyled contact">
						<li><p>
								<strong><i class="fa fa-envelope"></i> Mail Us:</strong> <a
									href="#">support@itcertification2.com</a>
							</p></li>
						<li>			
						</li>	

					</ul>
					<ul class="list-inline social-1">
						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
						<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
					</ul>
				</div>
			</div>
			<!--footer col-->

			<!--footer col-->
			<div class="col-md-4 col-sm-6 margin30">
				<div class="footer-col">
					<h3>Newsletter</h3>
					<p>To subscribe for news letters please add your email address
						here</p>
					<form role="form" class="subscribe-form">
						<div class="input-group">
							<input type="text" class="form-control"
								placeholder="Enter email to subscribe"> <span
								class="input-group-btn">
								<button class="btn  btn-theme-dark btn-lg" type="submit">Ok</button>
							</span>
						</div>
					</form>
				</div>
			</div>
			<!--footer col-->

		</div>
	</div>
</footer>