    <div class="list-group">
        <a href="$context$userinfo/" class="list-group-item $userinfo$">
            <span class="glyphicon  glyphicon-user"></span> User Info <span class="badge">1</span>
        </a>
        <a href="$context$examinfo/" class="list-group-item $exammenu$">
            <span class="glyphicon  glyphicon-user"></span> Exam History <span class="badge">$history$</span>
        </a>
    </div>

<!--sidebar-box-->