GRANT ALL PRIVILEGES ON cert.* TO 'cert_owner'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;

create database cert;

GRANT ALL PRIVILEGES ON cert.* TO 'cert_owner'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON cert.* TO 'cert_owner'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON cert.* TO 'cert_owner'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON certforum.* TO 'jforumuser'@'%' IDENTIFIED BY 'jforumuser123$$' WITH GRANT OPTION;

DROP TABLE IF EXISTS COURSE ;
DROP TABLE IF EXISTS PAGE ;
DROP TABLE IF EXISTS USERS ;
DROP TABLE IF EXISTS VENDOR ;
DROP TABLE IF EXISTS CERTIFICATION ;
DROP TABLE IF EXISTS CERTIFICATION_COURSE ;
DROP TABLE IF EXISTS ASSOC_URL;
DROP TABLE IF EXISTS VISITORS;
DROP TABLE IF EXISTS URL_KEYWORD;
DROP TABLE IF EXISTS MAIL_HISTORY;
DROP TABLE IF EXISTS QUESTION ;
DROP TABLE IF EXISTS ANSWER ;
DROP TABLE IF EXISTS EXPLANATION ;
DROP TABLE IF EXISTS OBJECTIVE ;
DROP TABLE IF EXISTS EXHIBIT ;
DROP TABLE IF EXISTS USER_SESSION;
DROP TABLE IF EXISTS USER_SESSION_HISTORY;
DROP TABLE IF EXISTS EXAM_HISTORY;
DROP TABLE IF EXISTS EXAM_HISTORY_RECORD;
DROP TABLE IF EXISTS EXTEND_PLAN; 
DROP TABLE IF EXISTS BLACKLIST;

CREATE TABLE ADMIN_LOG
(
   id int PRIMARY KEY NOT NULL,
   user_id text NOT NULL,
   login_time timestamp NOT NULL,
   ip_address text NOT NULL
)
;
CREATE UNIQUE INDEX PRIMARY ON ADMIN_LOG(id);

drop table USER_SESSION;
CREATE TABLE USER_SESSION (
  user_id VARCHAR(256) NOT NULL,
  session_id VARCHAR(64) NOT NULL,
  login_time TIMESTAMP NOT NULL,
  ip_address VARCHAR(256) NOT NULL,
  PRIMARY KEY(user_id, session_id)
);

drop tables EXAM_HISTORY;
CREATE TABLE EXAM_HISTORY (
  user_id VARCHAR(256) NOT NULL,
  session_id VARCHAR(64) NOT NULL,
  exam_name VARCHAR(256) NOT NULL,
  create_time TIMESTAMP NOT NULL,
  PRIMARY KEY(user_id, session_id, exam_name)
);

CREATE TABLE QUESTION_HISTORY (
  user_id VARCHAR(256) NOT NULL,
  session_id VARCHAR(512) NOT NULL,
  exam_name VARCHAR(256) NOT NULL,
  question_id INTEGER NOT NULL,
  correct BOOL DEFAULT FALSE,
  PRIMARY KEY(user_id, session_id, exam_name, question_id)
);


CREATE TABLE USER_SESSION_HISTORY (
  id INTEGER  NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(256) NOT NULL,
  login_time TIMESTAMP NOT NULL,
  ip_address VARCHAR(256) NOT NULL,
  exam_name VARCHAR(256) NOT NULL,
  PRIMARY KEY(id)
);


CREATE TABLE EXAM_HISTORY (
  session_id VARCHAR(512)  NOT NULL,
  user_id VARCHAR(256) NOT NULL,
  exam_name VARCHAR(256) NOT NULL,
  create_time TIMESTAMP NOT NULL,
  PRIMARY KEY(session_id, user_id, exam_name)
);

CREATE TABLE EXAM_HISTORY_RECORD (
  session_id INTEGER  NOT NULL,
  user_id VARCHAR(256) NOT NULL,
  exam_name VARCHAR(256) NOT NULL,
  question_id INTEGER  NOT NULL,
  answers VARCHAR(16) NULL,
  correct VARCHAR(16) NULL,
  status BOOL NOT NULL,
  PRIMARY KEY(session_id, question_id)
);


CREATE TABLE VENDOR (
  vendor_id INTEGER  NOT NULL AUTO_INCREMENT,
  vendor_name VARCHAR(256) NULL,
  vendor_desc VARCHAR(1024) NULL,
  page_name VARCHAR(1024) NULL,
  info VARCHAR(4000) NULL,
  resources VARCHAR(4000) NULL,
  rank INTEGER,
  PRIMARY KEY(vendor_id)
);

alter table VENDOR add rank INTEGER DEFAULT 1;

CREATE TABLE CERTIFICATION (
  id INTEGER  NOT NULL AUTO_INCREMENT, 
  name VARCHAR(256) NULL,
  descr VARCHAR(256) NULL,
  page_name VARCHAR(1024) NULL,
  vendor_id INTEGER  NOT NULL, 
  prerequisite VARCHAR(4000) NULL,
  info VARCHAR(4000) NULL,
  recertification VARCHAR(4000) NULL,
  resources VARCHAR(4000) NULL,
  PRIMARY KEY(id),
  INDEX CERTIFICATION_FKIndex1(VENDOR_vendor_id)
);

alter table CERTIFICATION add vendor_id INTEGER NOT NULL;
update CERTIFICATION set vendor_id=VENDOR_vendor_id;
alter table CERTIFICATION drop VENDOR_vendor_id;

CREATE TABLE USERS (
  user_id VARCHAR(256) NOT NULL,
  password VARCHAR(1024) NOT NULL,
  email_address VARCHAR(256) NOT NULL,
  address VARCHAR(1024) NULL,
  city VARCHAR(1024) NULL,
  state VARCHAR(1024) NULL,
  phone VARCHAR(256) NULL,
  country VARCHAR(1024) NULL,
  zipcode VARCHAR(256) NULL,
  ipaddress VARCHAR(256) NULL,
  user_role int NOT NULL,
  receive_mail BOOL NULL,
  activation_code INTEGER NOT NULL,
  status INTEGER NOT NULL,
  invalid_login INTEGER NOT NULL,
  signup_time TIMESTAMP NULL,
  PRIMARY KEY(user_id)
);
alter table USERS modify password_2 VARCHAR(1024) NOT NULL;

CREATE TABLE CERTIFICATION_EXAM
(
   cert_id int NOT NULL,
   exam_name VARCHAR(256) NOT NULL,
   PRIMARY KEY(cert_id, exam_name),
  INDEX CERTIFICATION_EXAM_FKIndex1(cert_id),
  INDEX CERTIFICATION_EXAM_FKIndex2(exam_name)
);

insert into CERTIFICATION_EXAM
select CERTIFICATION_ID, COURSE_course_name from CERTIFICATION_COURSE;
commit;

CREATE TABLE PAGE (
  page_id INTEGER NOT NULL AUTO_INCREMENT,
  page_name VARCHAR(256) NOT NULL,
  page_desc VARCHAR(1024) NULL,
  title VARCHAR(1024) NULL,
  PRIMARY KEY(page_id)
);

CREATE TABLE EXAM
(
   exam_name VARCHAR(256) PRIMARY KEY NOT NULL,
   exam_desc VARCHAR(4000),
   page_name VARCHAR(256),
   retired_date date,
   update_date date,
   file_name VARCHAR(256),
   file_location VARCHAR(256) NOT NULL,
   ver varchar(32),
   exam_time int,
   valid int,
   passing_score int,
   question_format VARCHAR(256),
   exam_title VARCHAR(256),
   resources VARCHAR(4000),
   prerequisite VARCHAR(4000),
   questions int,
   explanation bit,
   vendor_id int,
   vendor_name VARCHAR(256),
   rank int DEFAULT 1
);

CREATE TABLE VISITORS (
  id INTEGER NOT NULL AUTO_INCREMENT,
  ip_address VARCHAR(256) NOT NULL,
  site VARCHAR(256) NOT NULL,
  page VARCHAR(256) NOT NULL,
  referer VARCHAR(1024) NOT NULL,
  login_time TIMESTAMP NOT NULL,
  PRIMARY KEY(id)
);

CREATE OR REPLACE VIEW EXAM_VIEW AS
SELECT E.*, V.rank as vendor_rank
FROM EXAM E, VENDOR V
WHERE 
E.vendor_id=V.vendor_id
ORDER BY E.exam_name;

CREATE TABLE OBJECTIVE (
  id INTEGER  NOT NULL,
  exam_name VARCHAR(128) NOT NULL,
  title VARCHAR(1024) NOT NULL,
  order_number INTEGER  NOT NULL,
  text VARCHAR(4000) NULL,
  PRIMARY KEY(exam_name, id)
);

CREATE TABLE QUESTION (
  id INTEGER  NOT NULL,
  exam_name VARCHAR(128) NOT NULL,
  t VARCHAR(32) NOT NULL,
  s VARCHAR(32) NULL,
  exp VARCHAR(4000) NULL,
  choice BOOL NOT NULL,
  PRIMARY KEY(exam_name, id)
);



CREATE TABLE EXHIBIT (
  id INTEGER  NOT NULL,
  exam_name VARCHAR(128) NOT NULL,
  question_id INTEGER NOT NULL,
  order_number INTEGER  NOT NULL,
  exhibit_type INTEGER NOT NULL,
  text VARCHAR(4000) NULL,
  text2 VARCHAR(4000) NULL,
  text3 VARCHAR(4000) NULL,
  ip VARCHAR(32) NULL,
  dnd VARCHAR(4000) NULL,
  PRIMARY KEY(exam_name, question_id, id)
);

CREATE TABLE ANSWER (
  id INTEGER  NOT NULL,
  exam_name VARCHAR(128) NOT NULL,
  question_id INTEGER  NOT NULL,
  text VARCHAR(4000) NULL,
  is_correct BOOL NOT NULL,
  PRIMARY KEY(exam_name, question_id, id)
);

CREATE TABLE EXPLANATION (
  id INTEGER  NOT NULL,
  exam_name VARCHAR(128) NOT NULL,
  question_id INTEGER  NOT NULL,
  text VARCHAR(4000) NULL,
  text2 VARCHAR(4000) NULL,
  text3 VARCHAR(4000) NULL,
  image VARCHAR(128) NULL,	
  exp_type INTEGER NOT NULL,
  PRIMARY KEY(exam_name, question_id, id)
);

CREATE TABLE BLACKLIST (
  ipaddress VARCHAR(128)  NOT NULL,
  PRIMARY KEY(ipaddress)
);

DROP TABLE IF EXISTS EXAM_CREATION;
CREATE TABLE EXAM_CREATION (
  user_id VARCHAR(128)  NOT NULL,
  exam_name VARCHAR(128)  NOT NULL,
  create_time TIMESTAMP NOT NULL,
  ip_address VARCHAR(32) NULL,
  PRIMARY KEY(user_id, exam_name)
);

DROP TABLE IF EXISTS RSS;
CREATE TABLE RSS (
  source VARCHAR(128)  NOT NULL,
  copyright VARCHAR(256) NULL,
  update_time TIMESTAMP NOT NULL,  
  url VARCHAR(512)  NULL,
  PRIMARY KEY(source)
);

DROP TABLE IF EXISTS RSS_ITEM;
CREATE TABLE RSS_ITEM (
  id INTEGER  NOT NULL AUTO_INCREMENT,
  source VARCHAR(128)  NOT NULL,
  url VARCHAR(512)  NULL,
  descr VARCHAR(4000) NULL,
  title VARCHAR(512) NULL,
  publish_date DATE   NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS STATISTIC;
CREATE TABLE STATISTIC (
  id INTEGER  NOT NULL AUTO_INCREMENT,
  item_id VARCHAR(128)  NOT NULL,
  count INTEGER NULL DEFAULT 1,
  access_time TIMESTAMP NOT NULL,  
  ipaddress VARCHAR(64)  NULL,
  location VARCHAR(256)  NULL,
  browser VARCHAR(512)  NULL,
  referer VARCHAR(256)  NULL DEFAULT 'direct',
  PRIMARY KEY(id)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON cert.* TO 'cert_admin'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON cert.* TO 'cert_admin'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT SELECT ON cert.* TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.USERS TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE ON cert.SHOPPING_CART_RECORD TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_ORDER TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.VISITORS TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.USER_SESSION TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.USER_SESSION_HISTORY TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_HISTORY TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_ORDER_TRANSACTION TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_HISTORY_RECORD TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.BLACKLIST TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE  ON cert.RSS TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE  ON cert.RSS_ITEM TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT SELECT ON cert.* TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.USERS TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE ON cert.SHOPPING_CART_RECORD TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_ORDER TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.VISITORS TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.USER_SESSION TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.USER_SESSION_HISTORY TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_HISTORY TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_ORDER_TRANSACTION TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_HISTORY_RECORD TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.BLACKLIST TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE  ON cert.RSS TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE  ON cert.RSS_ITEM TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT SELECT ON cert.* TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.USERS TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE ON cert.SHOPPING_CART_RECORD TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_ORDER TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.VISITORS TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.USER_SESSION TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.USER_SESSION_HISTORY TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_HISTORY TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_HISTORY_RECORD TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.EXAM_ORDER_TRANSACTION TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT ON cert.BLACKLIST TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE  ON cert.RSS TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE ON cert.RSS_ITEM TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE ON cert.STATISTIC TO 'cert_user'@'192.168.1.%' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE ON cert.STATISTIC TO 'cert_user'@'localhost' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
GRANT UPDATE, INSERT, DELETE ON cert.STATISTIC TO 'cert_user'@'127.0.0.1' IDENTIFIED BY 'seattle2006$$' WITH GRANT OPTION;
